version: '3'

services:
  ladesa-reverse-proxy:
    image: traefik:v3.1

    networks:
      - ladesa-net

    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"

    command: 
      # 
      - "--api.debug=true"
      - "--log.level=DEBUG"
      #
      - "--api.insecure=false"
      - "--api.dashboard=true"
      # 
      - "--accesslog=true"
      # 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ladesa-net"
      #
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      #
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      #

    volumes:
      #
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      #

    labels:
      #
      - "traefik.enable=true"
      #
      - "traefik.http.routers.traefik.rule=Host(`traefik.ladesa.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      #
      - "traefik.http.routers.traefik-insecure.rule=Host(`traefik.ladesa.localhost`)"
      - "traefik.http.routers.traefik-insecure.entrypoints=web"
      - "traefik.http.routers.traefik-insecure.service=api@internal"
      #

    logging:
      driver: "json-file"
      options:
        max-size: "1m"

    # healthcheck:
    #   test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:8080/ping || exit 1"]
    #   interval: 3s
    #   retries: 12

networks:
  ladesa-net:
    external: true